### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by CharlesRuntime** [goodow/GDLiveStreaming#10]
下载下来  项目里pods.xcodeproj是红的   pod insatall 中说 “[!] No podspec found for `VideoCore` in `../VideoCore`”     根本运行不了    求解答   最近遇到好多这种问题没解决了 - -

**Comment by larrytin** [comment]
刚刚更新了README.md, 需要在根目录下执行`git submodule update --init`

To run the example project:
1. Clone the repo, run `git submodule update --init` in the root directory.
2. Run `pod install` from the Example directory and open `GDLiveStreaming.xcworkspace` file.

**Comment by CharlesRuntime** [comment]
fatal: Not a git repository (or any of the parent directories): .git   是cd到GDLiveStreaming-master 再执行语句吧？  反正哪个目录下都试了  - -

**Comment by CharlesRuntime** [comment]
还有  我是download下来的    克隆的没事么

**Comment by larrytin** [comment]
修改[Podfile](https://github.com/goodow/GDLiveStreaming/blob/master/Example/Podfile)文件, 将

```
pod 'VideoCore', path: '../VideoCore'
```

替换为

```
pod 'VideoCore', :git => 'https://github.com/goodow/VideoCore.git'
```
