### ISSUE TITLE
你好 ，我这边pod 有问题  我的cocoapods 是 最新的1.0.1 不知道是不是这个原因，几个库pod不下来

### ISSUE THREAD

**Issue by Demonsword27** [goodow/GDLiveStreaming#13]

**Comment by larrytin** [comment]
提示什么信息?

**Comment by Demonsword27** [comment]
Last login: Mon Jun 27 10:20:46 on ttys001
wbqdeMac-mini:~ wbq$ cd /Users/wbq/Downloads/GDLiveStreaming-master/Example 
wbqdeMac-mini:Example wbq$ pod install
Analyzing dependencies
Fetching podspec for `GDLiveStreaming` from `../`
Fetching podspec for `VideoCore` from `../VideoCore`
[!] No podspec found for `VideoCore` in `../VideoCore`
wbqdeMac-mini:Example wbq$

**Comment by Demonsword27** [comment]
我觉得蛮怪的  我按照的你的步骤，cd example  然后 pod install

**Comment by larrytin** [comment]
请按README的提示进行操作

![image](https://cloud.githubusercontent.com/assets/4640250/16367230/f0ae30fe-3c53-11e6-958d-3a241ce2132a.png)

**Comment by Demonsword27** [comment]
3Q....没注意。。谢谢哈
