### ISSUE TITLE
pod出错

### ISSUE THREAD

**Issue by congni** [goodow/GDLiveStreaming#14]
Pre-downloading: `GDLiveStreaming` from `https://github.com/goodow/GDLiveStreaming.git`

[!] Error installing GDLiveStreaming
[!] /usr/bin/git clone https://github.com/goodow/GDLiveStreaming.git /var/folders/f3/x1yq0jk97fd4jxd8xyq7g1h40000gn/T/d20160701-59425-1xaa9ae --template= --single-branch --depth 1

Cloning into '/var/folders/f3/x1yq0jk97fd4jxd8xyq7g1h40000gn/T/d20160701-59425-1xaa9ae'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed

**Comment by larrytin** [comment]
这是因为国内网络环境不好的原因吧
