### ISSUE TITLE
in the demo code,error will occur when I set the videoSize from CGSizeMake(720,1280) to CGSizeMake(360,640),

### ISSUE THREAD

**Issue by bellchen** [goodow/GDLiveStreaming#5]
in the demo code,error will occur when I set the videoSize from CGSizeMake(720,1280) to CGSizeMake(360,640);
here is the code 
`CGSize size = CGSizeMake(360, 640); // it was (720,1280)`
`GDLRawDataOutput *rawDataOutput = [[GDLRawDataOutput alloc] initWithVideoCamera:_videoCamera
withImageSize:size];`
`[_videoCamera addTarget:rawDataOutput];`

and here is the error:
`Null texture!159: Error creating texture! (-6683)Null texture!159: Error creating texture! (-6683)Null texture!159: Error creating texture! (-6683)Null texture!159: Error creating texture! (-6683)Null texture!159: Error creating texture!...`
repeat `Null texture!159: Error creating texture! (-6683)` many time

**Comment by larrytin** [comment]
是否用的GPUImage采集视频呢

**Comment by bellchen** [comment]
是的

**Comment by zas132** [comment]
you can use this:
i has run app and it works.
code is:

 GDLRawDataOutput *rtmpOutput = [[GDLRawDataOutput alloc] initWithVideoCamera:_videoCamera withImageSize:CGSizeMake(400, 712)];

**Comment by zas132** [comment]
or use this code:
GDLRawDataOutput *rtmpOutput = [[GDLRawDataOutput alloc] initWithVideoCamera:_videoCamera withImageSize:CGSizeMake(368, 656)];

**Comment by larrytin** [comment]
我使用如下代码没有成功:
```
GPUImageFilter *filter = [[GPUImageLanczosResamplingFilter alloc] init];
[filter forceProcessingAtSizeRespectingAspectRatio:size];
```

**Comment by Guikunzhi** [comment]
设置CGSize size = CGSizeMake(368, 640); 就可以了，因为你输入(360, 640)，GPUImageRawDataOutput输出还是 368 \* 640的
