### ISSUE TITLE
OGL  error  Invalid Operation

### ISSUE THREAD

**Issue by L1MeN9Yu** [goodow/GDLiveStreaming#6]
get "OGL(/Pods/VideoCore/api/iOS/VCPreviewView.mm):: 253: Invalid Operation" error after `[_videoCamera addTarget:rawDataOutput];`
Any idea?

**Comment by L1MeN9Yu** [comment]
Maybe libPods.a is the old one

**Comment by larrytin** [comment]
执行 pod update 看看
