### ISSUE TITLE
在Example目录运行 pod install 出错

### ISSUE THREAD

**Issue by cndacai** [goodow/GDLiveStreaming#8]
你好，感谢提供这么好的项目，按你的提示在clone项目后，在 Example 目录执行 pod install 出错，如下

owendeiMac:Example owen$ pod install
Analyzing dependencies
Fetching podspec for `GDLiveStreaming` from `../`
Fetching podspec for `VideoCore` from `../VideoCore`
[!] No podspec found for `VideoCore` in `../VideoCore`

请问如何解决？

**Comment by larrytin** [comment]
在根目录执行如下命令:

```
git submodule update --init
```
