### ISSUE TITLE
请问怎么开启美颜？

### ISSUE THREAD

**Issue by zas132** [goodow/GDLiveStreaming#9]
这种方法开启不了GPUImage滤镜

GPUImageVideoCamera *videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionBack];
videoCamera.outputImageOrientation = UIInterfaceOrientationPortrait;

GPUImageFilter *customFilter = [[GPUImageFilter alloc] initWithFragmentShaderFromFile:@"CustomShader"];
GPUImageView *filteredVideoView = [[GPUImageView alloc] initWithFrame:CGRectMake(0.0, 0.0, viewWidth, viewHeight)];

// Add the view somewhere so it's visible

[videoCamera addTarget:customFilter];
[customFilter addTarget:filteredVideoView];

**Comment by larrytin** [comment]
会不会是"CustomShader"这个文件的问题, 试试[GPUImageBeautifyFilter](https://github.com/goodow/GDLiveStreaming/blob/master/GDLiveStreaming/Classes/filter/GPUImageBeautifyFilter.h):

```
GPUImageBeautifyFilter *beautifyFilter = [[GPUImageBeautifyFilter alloc] init];
```

或者[YUGPUImageHighPassSkinSmoothing](https://github.com/YuAo/YUGPUImageHighPassSkinSmoothing)

**Comment by zas132** [comment]
试过了也是不行。你测试一下？

**Comment by larrytin** [comment]
能不能看到预览画面, 有报错吗?

**Comment by zas132** [comment]
能看到预览，但是美颜没有效果加别的gpuimage滤镜
也没效果

**Comment by zas132** [comment]
能看到预览画面，也没没错，但是美颜没有效果，加上别的gpuimage滤镜也没有效果。

**Comment by zas132** [comment]
你可以添加gpuimage的反色滤镜测试下有没效果，我试的是没有起作用

**Comment by larrytin** [comment]
上传一份demo看下? 如果是使用了VideoCore, 需得包含这个修改https://github.com/goodow/VideoCore/commit/79110d04bfca20bd6072a9a0d1bc4120e0f29a8c

**Comment by zas132** [comment]
ok，明天上午发给你

**Comment by zas132** [comment]
包含这个修改goodow/VideoCore@79110d0

修改了，结果一样

**Comment by larrytin** [comment]
在Example里增加了变量[useSkinSmoothing](https://github.com/goodow/GDLiveStreaming/blob/master/Example/GDLiveStreaming/GDLViewController.m#L59), 修改为YES开启美颜

```
BOOL useSkinSmoothing = YES;
```

https://github.com/goodow/GDLiveStreaming/commit/0b18652b8391c09d8d0d105a7ce6c1d760bdb80b

**Comment by zas132** [comment]
thanks

**Comment by zas132** [comment]
谢谢，已经可以运行了，很好
